//

const searchSeed = [
	{
		_id: 1,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p1.png',
		images: [],
	},
	{
		_id: 2,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p2.png',
		images: [],
	},
	{
		_id: 3,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p3.png',
		images: [],
	},
	{
		_id: 4,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p4.png',
		images: [],
	},
	{
		_id: 5,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p5.png',
		images: [],
	},
	{
		_id: 6,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p6.png',
		images: [],
	},
	{
		_id: 7,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p7.png',
		images: [],
	},
	{
		_id: 8,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p1.png',
		images: [],
	},
	{
		_id: 9,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p2.png',
		images: [],
	},
	{
		_id: 10,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p3.png',
		images: [],
	},
	{
		_id: 4,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p4.png',
		images: [],
	},
	{
		_id: 5,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p5.png',
		images: [],
	},
	{
		_id: 6,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p6.png',
		images: [],
	},
	{
		_id: 7,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p7.png',
		images: [],
	},
	{
		_id: 1,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p1.png',
		images: [],
	},
	{
		_id: 2,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p2.png',
		images: [],
	},
	{
		_id: 3,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p3.png',
		images: [],
	},
	{
		_id: 4,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p4.png',
		images: [],
	},
	{
		_id: 5,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p5.png',
		images: [],
	},
	{
		_id: 6,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p6.png',
		images: [],
	},
	{
		_id: 7,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p7.png',
		images: [],
	},
	{
		_id: 1,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p1.png',
		images: [],
	},
	{
		_id: 2,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p2.png',
		images: [],
	},
	{
		_id: 3,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p3.png',
		images: [],
	},
	{
		_id: 4,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p4.png',
		images: [],
	},
	{
		_id: 5,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p5.png',
		images: [],
	},
	{
		_id: 6,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p6.png',
		images: [],
	},
	{
		_id: 7,
		name: 'Live Fresh Premium Beef Bone-In [Approx 1kg]',
		price: '699',
		unit: 'kg',
		symbol: '৳',
		displayImage: '/test/p7.png',
		images: [],
	},
];

export default searchSeed;
